language: swift
os: osx
osx_image: xcode11
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8

before_install:
  - gem install bundler --pre --no-document --quiet
  - bundle install --quiet

script:
  - fastlane test
  - fastlane build
  - pod lib lint --swift-version=5.0

after_success:
  - bash <(curl -s https://codecov.io/bash) -J '^ValidationToolkit$';
