language: objective-c
osx_image: xcode8
env:
  global:
  - FRAMEWORK_NAME=Validator
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=ValidationKit.xcproj
  - IOS_FRAMEWORK_SCHEME="ValidationKit iOS"
  - OSX_FRAMEWORK_SCHEME="ValidationKit macOS"
  - TVOS_FRAMEWORK_SCHEME="ValidationKit tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="ValidationKit watchOS"
  - IOS_SDK=iphonesimulator10.0
  - OSX_SDK=macosx10.11
  - TVOS_SDK=appletvsimulator10.0
  - WATCHOS_SDK=watchsimulator3.0
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="YES"
    - DESTINATION="OS=8.2,name=iPhone 5"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"
    - DESTINATION="OS=8.3,name=iPhone 5S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"
    - DESTINATION="OS=8.4,name=iPhone 6"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"
    - DESTINATION="OS=9.0,name=iPhone 6"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"
    - DESTINATION="OS=9.1,name=iPhone 6 Plus"      SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"
    - DESTINATION="OS=9.2,name=iPhone 6S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"
    - DESTINATION="OS=9.3,name=iPhone 6S Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"
    - DESTINATION="arch=x86_64"                    SCHEME="$OSX_FRAMEWORK_SCHEME"     SDK="$OSX_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
    - DESTINATION="OS=9.2,name=Apple TV 1080p"     SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO"
    - DESTINATION="OS=2.2,name=Apple Watch - 42mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK" RUN_TESTS="NO"  BUILD_EXAMPLE="NO"  POD_LINT="NO"
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- gem install xcpretty
before_script: 
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
script:
- set -o pipefail

# Build Framework in Debug and Run Tests if specified
- if [ $RUN_TESTS == "YES" ]; then
  xcodebuild -project "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
else
  xcodebuild -project "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
fi

# Build Framework in Release and Run Tests if specified
- if [ $RUN_TESTS == "YES" ]; then
  xcodebuild -project "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
else
  xcodebuild -project "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
fi

deploy:
  provider: releases
  api_key:
    secure: M+WIqcOkXlph4+5/Y4y5C+GfYEF5jcPB1QxpvurUAMKUhhknQKlvFokcqKCtJWJqCoPoHrhCgXQ7UdF/XoWbV1+585HLOjksXA6ZchWFDmxsPrq4eiIvY2scY3t9rTaSEd0TbAL1m9IlJyFwOJuPrMrCX8Lk8L0T5iscfIQkvRkYfUXtxcWXlhMVi2M9LTFo8SJmG3x8uyTESh94R5qYWh37Vm1MhiVHgl3M/N0g4zIlk6Q0KZlNOfEA5Gncxyr5hwGAsN7UcwrVD35ru8tyATcpM8+YGD5P9aN8ABuNymt84NEqlKyOBbJvzx+SQ3BXrkr1HyqQrin9UuaTJb1KlGmScbmT1NjestLkUVKSbVdAkzYKGjM4PzU5vcPO2Sl8QujpNO779e+Czuj3FF3IQ1tqs1zcavb7M/DWVzoGYsGs+iIW49KsP/LjcA0HHcLobqXtxaRWw2Oo/cj/NmAt7NWDGzMeJiUlpnOeuyNs51LKSdfyV15APQwIPoblIer+lDTja0P8nlP1kCd2ajG4O8XxvioFvoNGpS/77M+Jqu6iKIClZySafXu2fjbEvxb4IRKt7E4TP6Ia6k5m9FxVlEWApNmZKcmC5XzBYq/83NNSe04YdmhUM/30fZdkQmhHyY2v+YacxzYtHFy+cfZEncL/b+bsXrgwIMoD6+HvB0o=
  file: $FRAMEWORK_NAME.framework.zip
  skip_cleanup: true
  on:
    repo: alexcristea/brick-validator
    branch: develop
    tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash)