name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test --enable-code-coverage -v
      - uses: codecov/codecov-action@v1.2.1
