name: Push

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test --enable-code-coverage -v
      - name: Codecoverage
        run: |
          xcrun llvm-cov export -format="lcov" .build/debug/ValidationToolkitPackageTests.xctest/Contents/MacOS/ValidationToolkitPackageTests -instr-profile .build/debug/codecov/default.profdata > .build/info.lcov
          bash <(curl https://codecov.io/bash)
